// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Card struct {
	ID              string          `json:"id"`
	OracleID        string          `json:"oracle_id"`
	Name            string          `json:"name"`
	SetCode         string          `json:"set_code"`
	SetName         string          `json:"set_name"`
	CollectorNumber string          `json:"collector_number"`
	Rarity          string          `json:"rarity"`
	ManaCost        sql.NullString  `json:"mana_cost"`
	Cmc             sql.NullFloat64 `json:"cmc"`
	TypeLine        sql.NullString  `json:"type_line"`
	ImageUri        string          `json:"image_uri"`
	Raw             string          `json:"raw"`
	FetchedAt       string          `json:"fetched_at"`
}

type Collection struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	Name     string `json:"name"`
	IsShared int64  `json:"is_shared"`
}

type CollectionCard struct {
	CollectionID int64  `json:"collection_id"`
	CardID       string `json:"card_id"`
	Finish       string `json:"finish"`
	Quantity     int64  `json:"quantity"`
}

type Deck struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Format      string `json:"format"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type DeckCard struct {
	DeckID   int64  `json:"deck_id"`
	CardID   string `json:"card_id"`
	Zone     string `json:"zone"`
	Quantity int64  `json:"quantity"`
}

type User struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
}
